name: apollocode_flutter_utilities
description: A new Flutter package project.
version: 0.0.1
homepage: apollocode.ca
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  adaptive_breakpoints: ^0.1.4
  apollocode_dart_utilities:
    git: https://github.com/apollocode-ca/dart_utilities
  another_flushbar: ^1.12.29
  collection: ^1.17.0
  date_time_picker: ^2.1.0
  eventify: ^1.0.1
  firebase_auth: ^4.1.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.4.1+1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  flutter_web3: ^2.1.9
  flutter_widget_from_html_core: ^0.8.5+3
  go_router: ^5.1.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  jwt_decoder: ^2.0.1
  mask_text_input_formatter: ^2.4.0
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^4.1.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.6
  vector_math: ^2.1.2
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/icons/
  #   - assets/images/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
